### PR TITLE
Add simple navbar

### PR DESCRIPTION
**Pull request by gdim7**

### CODE REVIEW

**Comment by nathfreder** [comment]
This does not seem ready since their is no JSX. I'll be closing this, but feel free to open up another one are ask a question.

**Comment by gdim7** [comment]
But navbar is working just fine, what do I need the JSX for?

**Comment by nathfreder** [comment]
> But navbar is working just fine, what do I need the JSX for?

So that the browser render’a it, but if you can see it I may be wrong. I’ll test this.

**Comment by nathfreder** [comment]
I regret to inform you that this pull request will not be merged and I have added the `invalid` label to notify Hacktoberfest staff that this is not right. Your PR was rejected because it did not add anything, the navbar was already there. Thanks anyways and have a great day! 🎉

**Comment by gdim7** [comment]
No problem buddy, but the navbar wasn't there, I changed the CSS file and created the navbar.. It's ok though, have a nice day too!

**Comment by nathfreder** [comment]
Thanks @gdim7, sorry for the confusion 😞.

**Pull request closed without merging**
